export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
export const AUTOLOGIN_SUCCESS = 'AUTOLOGIN_SUCCESS';
export const AUTOLOGIN_FAILURE = 'AUTOLOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SIGNUP = {
    REQUEST: 'SIGNUP_REQUEST',
    SUCCESS: 'SIGNUP_SUCCESS',
    FAILURE: 'SIGNUP_FAILURE',        
}

